vk:
  name: 'vk'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'vk'
jwt:
  secret_key: "slatt"
postgres:
  username: "vk_intern"
  password: "vk_intern"
  host: "localhost"
  port: "5432"
  name: "vk_intern"
  pool_max: 10

#rabbitmq:
#  rpc_server_exchange: 'rpc_server'
#  rpc_client_exchange: 'rpc_client'