vk:
  name: 'vk'
  version: '1.0.0'

http:
  port: '8000'

logger:
  log_level: 'debug'
  rollbar_env: 'vk'
jwt:
  secret_key: "slatt"
postgres:
  username: "docker_vk"
  password: "docker_vk"
  host: "db"
  port: "6543"
  name: "docker_vk"
  pool_max: 10
